// TEMPORARY DATA

export let role = "admin";

export const teachersData = [
    {
        id: 1,
        teacherId: "0987654321",
        name: "John Doe",
        surName: "Le",
        email: "john@doe.com",
        photo: "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
        phone: "0987654321",
        subjects: ["Math", "Geometry"],
        classes: ["1B", "2A", "3C"],
        address: "123 Main St, Anytown, USA",
    },
    {
        id: 2,
        teacherId: "0987654321",
        name: "Jane Doe",
        surName: "Le",
        email: "jane@doe.com",
        photo: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
        phone: "0987654321",
        subjects: ["Physics", "Chemistry"],
        classes: ["5A", "4B", "3C"],
        address: "123 Main St, Anytown, USA",
    },
    {
        id: 3,
        teacherId: "0987654321",
        name: "Mike Geller",
        surName: "Le",
        email: "mike@geller.com",
        photo: "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
        phone: "0987654321",
        subjects: ["Biology"],
        classes: ["5A", "4B", "3C"],
        address: "123 Main St, Anytown, USA",
    },
    {
        id: 4,
        teacherId: "0987654321",
        name: "Jay French",
        surName: "Le",
        email: "jay@gmail.com",
        photo: "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
        phone: "0987654321",
        subjects: ["History"],
        classes: ["5A", "4B", "3C"],
        address: "123 Main St, Anytown, USA",
    },
    {
        id: 5,
        teacherId: "0987654321",
        name: "Jane Smith",
        surName: "Le",
        email: "jane@gmail.com",
        photo: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
        phone: "0987654321",
        subjects: ["Music", "History"],
        classes: ["5A", "4B", "3C"],
        address: "123 Main St, Anytown, USA",
    },
    {
        id: 6,
        teacherId: "0987654321",
        name: "Anna Santiago",
        surName: "Le",
        email: "anna@gmail.com",
        photo: "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
        phone: "0987654321",
        subjects: ["Physics"],
        classes: ["5A", "4B", "3C"],
        address: "123 Main St, Anytown, USA",
    },
    {
        id: 7,
        teacherId: "0987654321",
        name: "Allen Black",
        surName: "Le",
        email: "allen@black.com",
        photo: "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
        phone: "0987654321",
        subjects: ["English", "Spanish"],
        classes: ["5A", "4B", "3C"],
        address: "123 Main St, Anytown, USA",
    },
    {
        id: 8,
        teacherId: "0987654321",
        name: "Ophelia Castro",
        surName: "Le",
        email: "ophelia@castro.com",
        photo: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
        phone: "0987654321",
        subjects: ["Math", "Geometry"],
        classes: ["5A", "4B", "3C"],
        address: "123 Main St, Anytown, USA",
    },
    {
        id: 9,
        teacherId: "0987654321",
        name: "Derek Briggs",
        surName: "Le",
        email: "derek@briggs.com",
        photo: "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
        phone: "0987654321",
        subjects: ["Literature", "English"],
        classes: ["5A", "4B", "3C"],
        address: "123 Main St, Anytown, USA",
    },
    {
        id: 10,
        teacherId: "0987654321",
        name: "John Glover",
        surName: "Le",
        email: "john@glover.com",
        photo: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
        phone: "0987654321",
        subjects: ["Biology"],
        classes: ["5A", "4B", "3C"],
        address: "123 Main St, Anytown, USA",
    },
];

export const studentsData = [
    {
        id: 1,
        studentId: "0987654321",
        name: "John Doe",
        surName: "Le",
        email: "john@doe.com",
        photo: "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
        phone: "0987654321",
        grade: 5,
        class: "1B",
        address: "123 Main St, Anytown, USA",
    },
    {
        id: 2,
        studentId: "0987654321",
        name: "Jane Doe",
        surName: "Le",
        email: "jane@doe.com",
        photo: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
        phone: "0987654321",
        grade: 5,
        class: "5A",
        address: "123 Main St, Anytown, USA",
    },
    {
        id: 3,
        studentId: "0987654321",
        name: "Mike Geller",
        surName: "Le",
        email: "mike@geller.com",
        photo: "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
        phone: "0987654321",
        grade: 5,
        class: "5A",
        address: "123 Main St, Anytown, USA",
    },
    {
        id: 4,
        studentId: "0987654321",
        name: "Jay French",
        surName: "Le",
        email: "jay@gmail.com",
        photo: "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
        phone: "0987654321",
        grade: 5,
        class: "5A",
        address: "123 Main St, Anytown, USA",
    },
    {
        id: 5,
        studentId: "0987654321",
        name: "Jane Smith",
        surName: "Le",
        email: "jane@gmail.com",
        photo: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
        phone: "0987654321",
        grade: 5,
        class: "5A",
        address: "123 Main St, Anytown, USA",
    },
    {
        id: 6,
        studentId: "0987654321",
        name: "Anna Santiago",
        surName: "Le",
        email: "anna@gmail.com",
        photo: "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
        phone: "0987654321",
        grade: 5,
        class: "5A",
        address: "123 Main St, Anytown, USA",
    },
    {
        id: 7,
        studentId: "0987654321",
        name: "Allen Black",
        surName: "Le",
        email: "allen@black.com",
        photo: "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
        phone: "0987654321",
        grade: 5,
        class: "5A",
        address: "123 Main St, Anytown, USA",
    },
    {
        id: 8,
        studentId: "0987654321",
        name: "Ophelia Castro",
        surName: "Le",
        email: "ophelia@castro.com",
        photo: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
        phone: "0987654321",
        grade: 5,
        class: "5A",
        address: "123 Main St, Anytown, USA",
    },
    {
        id: 9,
        studentId: "0987654321",
        name: "Derek Briggs",
        surName: "Le",
        email: "derek@briggs.com",
        photo: "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
        phone: "0987654321",
        grade: 5,
        class: "5A",
        address: "123 Main St, Anytown, USA",
    },
    {
        id: 10,
        studentId: "0987654321",
        name: "John Glover",
        surName: "Le",
        email: "john@glover.com",
        photo: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
        phone: "0987654321",
        grade: 5,
        class: "5A",
        address: "123 Main St, Anytown, USA",
    },
];

export const subjectsData = [
    {
        id: 1,
        subjectId: "840000",
        name: "Math",
        teachers: ["Alice Phelps", "Russell Davidson"],
    },
    {
        id: 2,
        subjectId: "840000",
        name: "English",
        teachers: ["Manuel Becker", "Eddie Chavez"],
    },
    {
        id: 3,
        subjectId: "840000",
        name: "Physics",
        teachers: ["Lola Newman", "Darrell Delgado"],
    },
    {
        id: 4,
        subjectId: "840000",
        name: "Chemistry",
        teachers: ["Nathan Kelly", "Benjamin Snyder"],
    },
    {
        id: 5,
        subjectId: "840000",
        name: "Biology",
        teachers: ["Alma Benson", "Lina Collier"],
    },
    {
        id: 6,
        subjectId: "840000",
        name: "History",
        teachers: ["Hannah Bowman", "Betty Obrien"],
    },
    {
        id: 7,
        subjectId: "840000",
        name: "Geography",
        teachers: ["Lora French", "Sue Brady"],
    },
    {
        id: 8,
        subjectId: "840000",
        name: "Art",
        teachers: ["Harriet Alvarado", "Mayme Keller"],
    },
    {
        id: 9,
        subjectId: "840000",
        name: "Music",
        teachers: ["Gertrude Roy", "Rosa Singleton"],
    },
    {
        id: 10,
        subjectId: "840000",
        name: "Literature",
        teachers: ["Effie Lynch", "Brett Flowers"],
    },
];

export const classesData = [
    {
        id: 1,
        name: "1A",
        capacity: 40,
        grade: 1,
        supervisor: "Joseph Padilla",
    },
    {
        id: 2,
        name: "2B",
        capacity: 45,
        grade: 2,
        supervisor: "Blake Joseph",
    },
    {
        id: 3,
        name: "3C",
        capacity: 42,
        grade: 3,
        supervisor: "Tom Bennett",
    },
    {
        id: 4,
        name: "4B",
        capacity: 40,
        grade: 4,
        supervisor: "Aaron Collins",
    },
    {
        id: 5,
        name: "5A",
        capacity: 38,
        grade: 5,
        supervisor: "Iva Frank",
    },
    {
        id: 6,
        name: "5B",
        capacity: 40,
        grade: 5,
        supervisor: "Leila Santos",
    },
    {
        id: 7,
        name: "7A",
        capacity: 42,
        grade: 7,
        supervisor: "Carrie Walton",
    },
    {
        id: 8,
        name: "6B",
        capacity: 40,
        grade: 6,
        supervisor: "Christopher Butler",
    },
    {
        id: 9,
        name: "6C",
        capacity: 45,
        grade: 6,
        supervisor: "Marc Miller",
    },
    {
        id: 10,
        name: "6D",
        capacity: 42,
        grade: 6,
        supervisor: "Ophelia Marsh",
    },
];

export const lessonsData = [
    {
        id: 1,
        subject: "Math",
        class: "1A",
        teacher: "Tommy Wise",
    },
    {
        id: 2,
        subject: "English",
        class: "2A",
        teacher: "Rhoda Frank",
    },
    {
        id: 3,
        subject: "Science",
        class: "3A",
        teacher: "Della Dunn",
    },
    {
        id: 4,
        subject: "Social Studies",
        class: "1B",
        teacher: "Bruce Rodriguez",
    },
    {
        id: 5,
        subject: "Art",
        class: "4A",
        teacher: "Birdie Butler",
    },
    {
        id: 6,
        subject: "Music",
        class: "5A",
        teacher: "Bettie Oliver",
    },
    {
        id: 7,
        subject: "History",
        class: "6A",
        teacher: "Herman Howard",
    },
    {
        id: 8,
        subject: "Geography",
        class: "6B",
        teacher: "Lucinda Thomas",
    },
    {
        id: 9,
        subject: "Physics",
        class: "6C",
        teacher: "Ronald Roberts",
    },
    {
        id: 10,
        subject: "Chemistry",
        class: "4B",
        teacher: "Julia Pittman",
    },
];

export const examsData = [
    {
        id: 1,
        subject: "Math",
        class: "1A",
        teacher: "Martha Morris",
        date: "2025-04-12",
        startTime: "10:00 A.M",
    },
    {
        id: 2,
        subject: "English",
        class: "2A",
        teacher: "Randall Garcia",
        date: "2025-04-12",
        startTime: "10:00 A.M",
    },
    {
        id: 3,
        subject: "Science",
        class: "3A",
        teacher: "Myrtie Scott",
        date: "2025-04-12",
        startTime: "10:00 A.M",
    },
    {
        id: 4,
        subject: "Social Studies",
        class: "1B",
        teacher: "Alvin Swanson",
        date: "2025-04-12",
        startTime: "10:00 A.M",
    },
    {
        id: 5,
        subject: "Art",
        class: "4A",
        teacher: "Mabelle Wallace",
        date: "2025-04-12",
        startTime: "10:00 A.M",
    },
    {
        id: 6,
        subject: "Music",
        class: "5A",
        teacher: "Dale Thompson",
        date: "2025-04-12",
        startTime: "10:00 A.M",
    },
    {
        id: 7,
        subject: "History",
        class: "6A",
        teacher: "Allie Conner",
        date: "2025-04-12",
        startTime: "10:00 A.M",
    },
    {
        id: 8,
        subject: "Geography",
        class: "6B",
        teacher: "Hunter Fuller",
        date: "2025-04-12",
        startTime: "10:00 A.M",
    },
    {
        id: 9,
        subject: "Physics",
        class: "7A",
        teacher: "Lois Lindsey",
        date: "2025-04-12",
        startTime: "10:00 A.M",
    },
    {
        id: 10,
        subject: "Chemistry",
        class: "8A",
        teacher: "Vera Soto",
        date: "2025-04-12",
        startTime: "10:00 A.M",
    },
];

export const assignmentsData = [
    {
        id: 1,
        subject: "Math",
        class: "1A",
        teacher: "Anthony Boone",
        dueDate: "2025-04-12",
    },
    {
        id: 2,
        subject: "English",
        class: "2A",
        teacher: "Clifford Bowen",
        dueDate: "2025-04-12",
    },
    {
        id: 3,
        subject: "Science",
        class: "3A",
        teacher: "Catherine Malone",
        dueDate: "2025-04-12",
    },
    {
        id: 4,
        subject: "Social Studies",
        class: "1B",
        teacher: "Willie Medina",
        dueDate: "2025-04-12",
    },
    {
        id: 5,
        subject: "Art",
        class: "4A",
        teacher: "Jose Ruiz",
        dueDate: "2025-04-12",
    },
    {
        id: 6,
        subject: "Music",
        class: "5A",
        teacher: "Katharine Owens",
        dueDate: "2025-04-12",
    },
    {
        id: 7,
        subject: "History",
        class: "6A",
        teacher: "Shawn Norman",
        dueDate: "2025-04-12",
    },
    {
        id: 8,
        subject: "Geography",
        class: "6B",
        teacher: "Don Holloway",
        dueDate: "2025-04-12",
    },
    {
        id: 9,
        subject: "Physics",
        class: "7A",
        teacher: "Franklin Gregory",
        dueDate: "2025-04-12",
    },
    {
        id: 10,
        subject: "Chemistry",
        class: "8A",
        teacher: "Danny Nguyen",
        dueDate: "2025-04-12",
    },
];
export const reportsData = [
    {
        id: 1,
        student: "John Doe",
        class: "1A",
        subject: "Math",
        semester: 1,
        year: "2024-2025",
        fifteenScore: 8.5,
        midtermScore: 8.0,
        finalScore: 9.0,
        averageScore: 8.5,
        behavior: "Khá",
    },
    {
        id: 2,
        student: "John Doe",
        class: "2A",
        subject: "English",
        semester: 1,
        year: "2024-2025",
        fifteenScore: 8.5,
        midtermScore: 8.0,
        finalScore: 9.0,
        averageScore: 8.5,
        behavior: "Giỏi",
    },
    {
        id: 3,
        student: "John Doe",
        class: "3A",
        subject: "Science",
        semester: 1,
        year: "2024-2025",
        fifteenScore: 8.5,
        midtermScore: 8.0,
        finalScore: 9.0,
        averageScore: 8.5,
        behavior: "Khá",
    },
    {
        id: 4,
        student: "John Doe",
        class: "1B",
        subject: "Social Studies",
        semester: 1,
        year: "2024-2025",
        fifteenScore: 8.5,
        midtermScore: 8.0,
        finalScore: 9.0,
        averageScore: 8.5,
        behavior: "Giỏi",
    },
];
export const resultsData = [
    {
        id: 1,
        subject: "Math",
        class: "1A",
        teacher: "John Doe",
        student: "John Doe",
        date: "2025-04-12",
        type: "15ph",
        score: 90,
    },
    {
        id: 2,
        subject: "English",
        class: "2A",
        teacher: "John Doe",
        student: "John Doe",
        date: "2025-04-12",
        type: "1 tiết",
        score: 90,
    },
    {
        id: 3,
        subject: "Science",
        class: "3A",
        teacher: "John Doe",
        student: "John Doe",
        date: "2025-04-12",
        type: "15ph",
        score: 90,
    },
    {
        id: 4,
        subject: "Social Studies",
        class: "1B",
        teacher: "John Doe",
        student: "John Doe",
        date: "2025-04-12",
        type: "Cuối kỳ",
        score: 90,
    },
    {
        id: 5,
        subject: "Art",
        class: "4A",
        teacher: "John Doe",
        student: "John Doe",
        date: "2025-04-12",
        type: "15ph",
        score: 90,
    },
    {
        id: 6,
        subject: "Music",
        class: "5A",
        teacher: "John Doe",
        student: "John Doe",
        date: "2025-04-12",
        type: "Cuối kỳ",
        score: 90,
    },
    {
        id: 7,
        subject: "History",
        class: "6A",
        teacher: "John Doe",
        student: "John Doe",
        date: "2025-04-12",
        type: "Cuối kỳ",
        score: 90,
    },
    {
        id: 8,
        subject: "Geography",
        class: "6B",
        teacher: "John Doe",
        student: "John Doe",
        date: "2025-04-12",
        type: "15ph",
        score: 90,
    },
    {
        id: 9,
        subject: "Physics",
        class: "7A",
        teacher: "John Doe",
        student: "John Doe",
        date: "2025-04-12",
        type: "1 tiết",
        score: 90,
    },
    {
        id: 10,
        subject: "Chemistry",
        class: "8A",
        teacher: "John Doe",
        student: "John Doe",
        date: "2025-04-12",
        type: "1 tiết",
        score: 90,
    },
];

export const eventsData = [
    {
        id: 1,
        title: "Lake Trip",
        class: "1A",
        date: "2025-04-12",
        startTime: "10:00",
        endTime: "11:00",
    },
    {
        id: 2,
        title: "Picnic",
        class: "2A",
        date: "2025-04-12",
        startTime: "10:00",
        endTime: "11:00",
    },
    {
        id: 3,
        title: "Beach Trip",
        class: "3A",
        date: "2025-04-12",
        startTime: "10:00",
        endTime: "11:00",
    },
    {
        id: 4,
        title: "Museum Trip",
        class: "4A",
        date: "2025-04-12",
        startTime: "10:00",
        endTime: "11:00",
    },
    {
        id: 5,
        title: "Music Concert",
        class: "5A",
        date: "2025-04-12",
        startTime: "10:00",
        endTime: "11:00",
    },
    {
        id: 6,
        title: "Magician Show",
        class: "1B",
        date: "2025-04-12",
        startTime: "10:00",
        endTime: "11:00",
    },
    {
        id: 7,
        title: "Lake Trip",
        class: "2B",
        date: "2025-04-12",
        startTime: "10:00",
        endTime: "11:00",
    },
    {
        id: 8,
        title: "Cycling Race",
        class: "3B",
        date: "2025-04-12",
        startTime: "10:00",
        endTime: "11:00",
    },
    {
        id: 9,
        title: "Art Exhibition",
        class: "4B",
        date: "2025-04-12",
        startTime: "10:00",
        endTime: "11:00",
    },
    {
        id: 10,
        title: "Sports Tournament",
        class: "5B",
        date: "2025-04-12",
        startTime: "10:00",
        endTime: "11:00",
    },
];

export const announcementsData = [
    {
        id: 1,
        title: "About 4A Math Test",
        class: "4A",
        date: "2025-04-12",
    },
    {
        id: 2,
        title: "About 3A Math Test",
        class: "3A",
        date: "2025-04-12",
    },
    {
        id: 3,
        title: "About 3B Math Test",
        class: "3B",
        date: "2025-04-12",
    },
    {
        id: 4,
        title: "About 6A Math Test",
        class: "6A",
        date: "2025-04-12",
    },
    {
        id: 5,
        title: "About 8C Math Test",
        class: "8C",
        date: "2025-04-12",
    },
    {
        id: 6,
        title: "About 2A Math Test",
        class: "2A",
        date: "2025-04-12",
    },
    {
        id: 7,
        title: "About 4C Math Test",
        class: "4C",
        date: "2025-04-12",
    },
    {
        id: 8,
        title: "About 4B Math Test",
        class: "4B",
        date: "2025-04-12",
    },
    {
        id: 9,
        title: "About 3C Math Test",
        class: "3C",
        date: "2025-04-12",
    },
    {
        id: 10,
        title: "About 1C Math Test",
        class: "1C",
        date: "2025-04-12",
    },
];

// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
// export const calendarEvents = [
//     {
//         title: "Math",
//         allDay: false,
//         start: new Date(2025, 3, 12, 8, 0),
//         end: new Date(2025, 3, 12, 8, 45),
//     },
//     {
//         title: "English",
//         allDay: false,
//         start: new Date(2025, 3, 12, 9, 0),
//         end: new Date(2025, 3, 12, 9, 45),
//     },
//     {
//         title: "Biology",
//         allDay: false,
//         start: new Date(2025, 3, 12, 10, 0),
//         end: new Date(2025, 3, 12, 10, 45),
//     },
//     {
//         title: "Physics",
//         allDay: false,
//         start: new Date(2025, 3, 12, 11, 0),
//         end: new Date(2025, 3, 12, 11, 45),
//     },
//     {
//         title: "Chemistry",
//         allDay: false,
//         start: new Date(2025, 3, 12, 13, 0),
//         end: new Date(2025, 3, 12, 13, 45),
//     },
//     {
//         title: "History",
//         allDay: false,
//         start: new Date(2025, 3, 12, 14, 0),
//         end: new Date(2025, 3, 12, 14, 45),
//     },
//     {
//         title: "English",
//         allDay: false,
//         start: new Date(2025, 3, 13, 9, 0),
//         end: new Date(2025, 3, 13, 9, 45),
//     },
//     {
//         title: "Biology",
//         allDay: false,
//         start: new Date(2025, 3, 13, 10, 0),
//         end: new Date(2025, 3, 13, 10, 45),
//     },
//     {
//         title: "Physics",
//         allDay: false,
//         start: new Date(2025, 3, 13, 11, 0),
//         end: new Date(2025, 3, 13, 11, 45),
//     },

//     {
//         title: "History",
//         allDay: false,
//         start: new Date(2025, 3, 13, 14, 0),
//         end: new Date(2025, 3, 13, 14, 45),
//     },
//     {
//         title: "Math",
//         allDay: false,
//         start: new Date(2025, 3, 14, 8, 0),
//         end: new Date(2025, 3, 14, 8, 45),
//     },
//     {
//         title: "Biology",
//         allDay: false,
//         start: new Date(2025, 3, 14, 10, 0),
//         end: new Date(2025, 3, 14, 10, 45),
//     },

//     {
//         title: "Chemistry",
//         allDay: false,
//         start: new Date(2025, 3, 14, 13, 0),
//         end: new Date(2025, 3, 14, 13, 45),
//     },
//     {
//         title: "History",
//         allDay: false,
//         start: new Date(2025, 3, 14, 14, 0),
//         end: new Date(2025, 3, 13, 14, 45),
//     },
//     {
//         title: "English",
//         allDay: false,
//         start: new Date(2025, 3, 15, 9, 0),
//         end: new Date(2025, 3, 15, 9, 45),
//     },
//     {
//         title: "Biology",
//         allDay: false,
//         start: new Date(2025, 3, 15, 10, 0),
//         end: new Date(2025, 3, 15, 10, 45),
//     },
//     {
//         title: "Physics",
//         allDay: false,
//         start: new Date(2025, 3, 15, 11, 0),
//         end: new Date(2025, 3, 15, 11, 45),
//     },

//     {
//         title: "History",
//         allDay: false,
//         start: new Date(2025, 3, 15, 14, 0),
//         end: new Date(2025, 3, 15, 14, 45),
//     },
//     {
//         title: "Math",
//         allDay: false,
//         start: new Date(2025, 3, 16, 8, 0),
//         end: new Date(2025, 3, 16, 8, 45),
//     },
//     {
//         title: "English",
//         allDay: false,
//         start: new Date(2025, 3, 16, 9, 0),
//         end: new Date(2025, 3, 16, 9, 45),
//     },

//     {
//         title: "Physics",
//         allDay: false,
//         start: new Date(2025, 3, 16, 11, 0),
//         end: new Date(2025, 3, 16, 11, 45),
//     },
//     {
//         title: "Chemistry",
//         allDay: false,
//         start: new Date(2025, 3, 16, 13, 0),
//         end: new Date(2025, 3, 16, 13, 45),
//     },
//     {
//         title: "History",
//         allDay: false,
//         start: new Date(2025, 3, 16, 14, 0),
//         end: new Date(2025, 3, 16, 14, 45),
//     },
// ];

export const calendarEvents = [
    {
        title: "Math",
        allDay: false,
        start: new Date(2025, 3, 7, 8, 0),
        end: new Date(2025, 3, 7, 8, 45),
    },
    {
        title: "English",
        allDay: false,
        start: new Date(2025, 3, 7, 9, 0),
        end: new Date(2025, 3, 7, 9, 45),
    },
    {
        title: "Biology",
        allDay: false,
        start: new Date(2025, 3, 7, 10, 0),
        end: new Date(2025, 3, 7, 10, 45),
    },
    {
        title: "Physics",
        allDay: false,
        start: new Date(2025, 3, 7, 11, 0),
        end: new Date(2025, 3, 7, 11, 45),
    },
    {
        title: "Chemistry",
        allDay: false,
        start: new Date(2025, 3, 7, 13, 0),
        end: new Date(2025, 3, 7, 13, 45),
    },
    {
        title: "History",
        allDay: false,
        start: new Date(2025, 3, 7, 14, 0),
        end: new Date(2025, 3, 7, 14, 45),
    },
    {
        title: "English",
        allDay: false,
        start: new Date(2025, 3, 8, 9, 0),
        end: new Date(2025, 3, 8, 9, 45),
    },
    {
        title: "Biology",
        allDay: false,
        start: new Date(2025, 3, 8, 10, 0),
        end: new Date(2025, 3, 8, 10, 45),
    },
    {
        title: "Physics",
        allDay: false,
        start: new Date(2025, 3, 8, 11, 0),
        end: new Date(2025, 3, 8, 11, 45),
    },

    {
        title: "History",
        allDay: false,
        start: new Date(2025, 3, 8, 14, 0),
        end: new Date(2025, 3, 8, 14, 45),
    },
    {
        title: "Math",
        allDay: false,
        start: new Date(2025, 3, 9, 8, 0),
        end: new Date(2025, 3, 9, 8, 45),
    },
    {
        title: "Biology",
        allDay: false,
        start: new Date(2025, 3, 9, 10, 0),
        end: new Date(2025, 3, 9, 10, 45),
    },

    {
        title: "Chemistry",
        allDay: false,
        start: new Date(2025, 3, 9, 13, 0),
        end: new Date(2025, 3, 9, 13, 45),
    },
    {
        title: "History",
        allDay: false,
        start: new Date(2025, 3, 9, 14, 0),
        end: new Date(2025, 3, 9, 14, 45),
    },
    {
        title: "English",
        allDay: false,
        start: new Date(2025, 3, 15, 9, 0),
        end: new Date(2025, 3, 15, 9, 45),
    },
    {
        title: "Biology",
        allDay: false,
        start: new Date(2025, 3, 15, 10, 0),
        end: new Date(2025, 3, 15, 10, 45),
    },
    {
        title: "Physics",
        allDay: false,
        start: new Date(2025, 3, 15, 11, 0),
        end: new Date(2025, 3, 15, 11, 45),
    },

    {
        title: "History",
        allDay: false,
        start: new Date(2025, 3, 15, 14, 0),
        end: new Date(2025, 3, 15, 14, 45),
    },
    {
        title: "Math",
        allDay: false,
        start: new Date(2025, 3, 16, 8, 0),
        end: new Date(2025, 3, 16, 8, 45),
    },
    {
        title: "English",
        allDay: false,
        start: new Date(2025, 3, 16, 9, 0),
        end: new Date(2025, 3, 16, 9, 45),
    },

    {
        title: "Physics",
        allDay: false,
        start: new Date(2025, 3, 16, 11, 0),
        end: new Date(2025, 3, 16, 11, 45),
    },
    {
        title: "Chemistry",
        allDay: false,
        start: new Date(2025, 3, 11, 13, 0),
        end: new Date(2025, 3, 11, 13, 45),
    },
    {
        title: "History",
        allDay: false,
        start: new Date(2025, 3, 11, 14, 0),
        end: new Date(2025, 3, 11, 14, 45),
    },
];
